### ISSUE TITLE
Program Crashes When No Argument Is Provided

### ISSUE THREAD

**Issue by CaveNightingale** [Andy-K-Sparklight/ACH#28]
In the correct version, running AlicornCH with less than 1 arguments lead to SIGSEGV without printing any help message.
I don't think it's a good design.

**Comment by Andy-K-Sparklight** [comment]
On Windows the memory management is not that strict and therefore not able to discover it in the first time.
But @litwak913 ran it on Arch Linux for many times without any crashes. TBO I'm quite interested in that.

**Comment by CaveNightingale** [comment]
https://github.com/Andy-K-Sparklight/Ari/commit/f973452f5206cfc487ce8459ba7648a19f8a3364#r98469830
