### ISSUE TITLE
Some Rendering Error in the Nagivation Bar in Modrinth

### ISSUE THREAD

**Issue by CaveNightingale** [Andy-K-Sparklight/ACH#29]
AlicornCH:
![2023-01-29 00-03-17屏幕截图](https://user-images.githubusercontent.com/51874645/215277200-5d1b9b0d-52aa-4f6b-a5b4-d6310cf62819.png)

Firefox:
![Screenshot 2023-01-29 at 00-04-43 Search Mods - Modrinth](https://user-images.githubusercontent.com/51874645/215277208-fc203323-a222-4746-8119-e4d36cd9fddf.png)

**Comment by CaveNightingale** [comment]
Besides, I wonder if there is a way to open Web Developer Tools in AlicornCH.

**Comment by Andy-K-Sparklight** [comment]
The tab bar highlight is related to the implmentation of Modrinth. We aren't able to figure out or solve it yet.
To open DevTools, right click the page and click "Inspect Elements" or similar option. Simply pressing F12 might work too, at least on Windows.
