### ISSUE TITLE
Ari Crash During Startup

### ISSUE THREAD

**Issue by CaveNightingale** [Andy-K-Sparklight/ACH#30]
```
[src/sys/Init.cc:28] Initializing system.
[src/sys/Storage.cc:52] Loading config from /home/billy/.alicorn-ch/Main.kv
[src/sys/Schedule.cc:60] Setting up UV thread.
[src/sys/Schedule.cc:65] UV thread created.
[src/core/platform/Finder.cc:43] Configured base path as "/home/billy/.alicorn-ch"
[src/core/network/Download.cc:314] Setting up download sync service.
[src/sys/Init.cc:45] Finished system initializing.
[src/extra/mod/provider/Modrinth.cc:250] Modrinth RPC server is listening.
[src/drivers/aria2/Aria2Driver.cc:106] Starting aria2 daemon with port 6801
[src/drivers/aria2/Aria2Driver.cc:113] Successfully started aria2 daemon with pid 2978954
非法指令 (核心已转储)
```
Some further research is needed.

**Comment by Andy-K-Sparklight** [comment]
Please use a debugger like gdb to give a detailed backtrace. Also, providing more information about the os environment will help to solve this.

**Comment by CaveNightingale** [comment]
I haven't got any stacktrace because I am not able to reproduce this.


Device Info:
Huawei CREF-16
Intel i5-12500H
Ubuntu 22.10



---Original---
From: "Annie K Rarity ***@***.***&gt;
Date: Sun, Jan 29, 2023 11:31 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Andy-K-Sparklight/Ari] AlicornCH Crashed (Issue #30)




 
Please use a debugger like gdb to give a detailed backtrace. Also, providing more information about the os environment will help to solve this.

**Comment by Nana-Sakura** [comment]
It was fixed in f973452f5206cfc487ce8459ba7648a19f8a3364 on macOS.
I will try to revert it on GNU.

**Comment by CaveNightingale** [comment]
> It was fixed in [f973452](https://github.com/Andy-K-Sparklight/Ari/commit/f973452f5206cfc487ce8459ba7648a19f8a3364) on macOS. I will try to revert it on GNU.

I think you are talking about #28

**Comment by Andy-K-Sparklight** [comment]
It might likely to happen when there is memory overwriting executable segments.
But possible similar crashes haven't been reported yet.

**Comment by Nana-Sakura** [comment]
It didn't revert, whatever it exited normally, with sigint, or even using sigkill, for nearly hundreds of times in gdb.
Fairly interesting.
Info:
Arch Linux AArch64

**Comment by CaveNightingale** [comment]
Since it's really hard to reproduce, I guess it was related to thread-safety in some way.
I've found that you spawn tons of threads as worker, so I'm going to have a look there.

**Comment by Andy-K-Sparklight** [comment]
As there are no further reports, this issue is marked as closed.
