### ISSUE TITLE
Fix UV Related Crash On UNIX

### ISSUE THREAD

**Issue by Andy-K-Sparklight** [Andy-K-Sparklight/ACH#4]

**Comment by Nana-Sakura** [comment]
Problem Behaviour:
<img width="682" alt="Screenshot 2022-12-07 at 14 06 36" src="https://user-images.githubusercontent.com/60061683/206101343-d6a5bc86-fc7f-45e6-b346-3587548e57b9.png">
It seems that libuv exited unexpectedly. Checking the source code and debugging.

**Comment by Andy-K-Sparklight** [comment]
Fixed the pipe crash in cc213676653156e8dcfeffce10d8ca1b7d8c8171
However, the fs crash needs to be confirmed.
