### ISSUE TITLE
Check Natives Might Missing Certain Packs

### ISSUE THREAD

**Issue by Andy-K-Sparklight** [Andy-K-Sparklight/ACH#8]

**Comment by Andy-K-Sparklight** [comment]
Certain libraries does not follow the naming pattern `natives-<platform>` and might cause it failed to be unpacked. e.g. `netty`

We need to test and find out.

If this is true, then we must unpack the libraries base on profile rather directory scanning. Since unpacking each jar to find native libraries is obviously tiresome.

@wxkj123

**Comment by Nana-Sakura** [comment]
It is now completed, only some issues on stability remaining.
