### ISSUE TITLE
Windows Not Displaying On OSX

### ISSUE THREAD

**Issue by Andy-K-Sparklight** [Andy-K-Sparklight/ACH#9]
~~It seems that seperated natives might cause game not to work.
Need to be confirmed, but we really need a module smarter than 'scan and unpack'.~~

It turns out that one extra argument cause game to crash.
However, we've updated the natives resolution module too.

**Comment by Nana-Sakura** [comment]
That is fairly troublesome actually. 
I do think we have to make diff on the module.
